branch-defaults:
  initial-commit:
    environment: todo-vish-gyana-dev
    group_suffix: null
  master:
    environment: todo-vish-gyana-dev
    group_suffix: null
environment-defaults:
  todo-vish-gyana-dev:
    branch: null
    repository: null
global:
  application_name: todo_vish_gyana
  branch: null
  default_ec2_keyname: aws-eb-todo-vgts
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
